config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments
  end

  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :user_id
  has_many :posts, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:comment))
		@comment.user_id = current_user.id if current_user
		@comment.save

		if @comment.save
			redirect_to post_path(@post)
		else
			render 'new'
		end
	end

	def edit
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
	end

	def update
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])

		if @comment.update(params[:comment].permit(:comment))
			redirect_to post_path(@post)
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order("created_at DESC")
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build


  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post creado con exito.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post editado con exito.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post eliminado con exito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:titulo, :contenido)
    end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def new
    @section = current_user.sections.build
  end

  def index
    @sections = Section.all.order("created_at DESC")
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="content">
    <p class="comment_content">
      <%= comment.comment %>
    </p>
    <p class="comment_author">
      <%= comment.user.email %>
    </p>
  </div>
  <div class="buttons">
    <%= link_to "Edit", edit_post_comment_path(comment.post, comment) %>
    <%= link_to "Delete", [comment.post, comment], method: :delete, data: { confirm: "Are you sure?" } %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for [@post, @post.comments.build] do |f| %>
  <% if user_signed_in? %>
    <%= f.input :comment %>
    <%= f.submit 'Comentar', class:"waves-effect waves-light btn"%>
  <% else %>
    <%= f.input :comment %>
    <%= link_to "Comentar", new_user_session_path, class:"waves-effect waves-light btn"  %>
  <% end %>
  <br>
<% end %>

app/views/comments/new.html.erb
<h1>Crear Comentario</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Volver', :back %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foroo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <style>
    { margin: 0; padding: 0; }

    html {
        background: url('https://png.pngtree.com/thumb_back/fw800/back_our/20190619/ourmid/pngtree-pizza-cartoon-yellow-poster-banner-background-image_133432.jpg') no-repeat center center fixed;
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
    }
</style>
    <div class="navbar-fixed">
    <nav class="orange darken-3">
        <div class="container">
          <a <h4> <div class='brand-logo'> <%= link_to 'BDCHAN Pizza Edition', root_path %>  </h4>  <img src='https://fueguillos.cl/wp-content/uploads/2015/01/peperoni.png' width=60 height=60 class="logo"> </div></a>
      </div>

      <!-- link_to "Rest in Pepperoni", root_path, class: "brand-logo center" %>
      img src='https://fueguillos.cl/wp-content/uploads/2015/01/peperoni.png' width=60 height=60> -->

        <ul class="right hide-on-med-and-down">
          <% if user_signed_in? %>
            <li><%= link_to 'Crear Post', new_post_path, class:"waves-effect waves-light btn" %></li>
            <li><%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %></li>
            <li><%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
          <% else %>
            <li><%= link_to "Registrarse", new_user_registration_path, :class => 'navbar-link'  %><li>
            <li><%= link_to "Iniciar Sesion", new_user_session_path, :class => 'navbar-link'  %><li>
        <% end %>

        </ul>
      </div>
    </nav>
    <p class="navbar-text float-right">
</p>
    </div>
    <div class="container">

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <b><%= form.label :titulo, 'Titulo' %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :contenido %>
    <%= form.text_area :contenido %></b>
  </div>
  <br>
  <div class="actions">
    <%= form.submit "Crear Post", class:"waves-effect waves-light btn" %>
  </div>
  <br>
<% end %>

app/views/posts/_form.html.haml
= simple_form_for @Post do |f|
  = f.input :title
  = f.input :content
  = f.submit

app/views/posts/edit.html.erb
<h1>Editando Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Ver', @post %> |
<%= link_to 'Volver', posts_path %>

app/views/posts/edit.html.haml
%h1 Edit Post

= render 'form'

= link_to "Cancel", post_path

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Posts</h3>

<table class="striped">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><h5><%= link_to post.titulo, post %><h5></td>
        <td><%=h truncate(post.contenido, :length => 80) %></td>
        <td>Por: <%= post.user.email %></td>
        <td><%= link_to 'Ver', post %></td>
        <td><%= link_to 'Editar', edit_post_path(post) %></td>
        <td><%= link_to 'Borrar', post, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/index.html.haml
- @posts.each do |post|
  %h2= link_to post.title, post
  %p= time_ago_in_words(post.created_at) + " ago"
  = link_to "New Post", new_post_path()

app/views/posts/new.html.erb
<h1>Crear Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Volver', posts_path %>

app/views/posts/new.html.haml
New Post

= render 'form' 

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<h3><%= @post.titulo %></h3>

<p>
  <%= @post.contenido %>
</p>

<p> Comentarios: <%= @post.comments.count %> </p>


<table>
        <thead>
          <tr>
              <th>Comentarios: <%= @post.comments.count %></th>
              <th></th>
          <tr>
        <thead>
<% @post.comments.each do |f|%>
        <tbody>
          <tr>
            <td><%= f.user.email %> </td>
            <td><%= f.comment %> </td>
          </tr>
        <tbody>
      <table>
        <%end%>


<br>
<%= render 'comments/form' %>

<br>

<%= link_to 'Editar', edit_post_path(@post) %> |
<%= link_to 'Volver', posts_path %>

app/views/posts/show.html.haml
%h1= @Post.title
%p= @Post.content

= link_to "Edit", edit_post_path(@Post)
= link_to "Delete", post_path(@Post), method: :delete, data: {confirm: "Are you sure?"}
= link_to "Home", root_path

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>